#!/bin/sh -e

ROTONDA_ETC="/etc/rotonda"

case "$1" in
purge)
    # Per https://www.debian.org/doc/debian-policy/ch-files.html#behavior
    # "configuration files must be preserved when the package is removed, and
    #  only deleted when the package is purged."
    if [ -d ${ROTONDA_ETC} ]; then
        rm -R ${ROTONDA_ETC}
    fi
    ;;
esac

#DEBHELPER#