{
 "title": "Rotonda Runtime Latest",
 "time": { "from": "now-5m", "to": "now" },
 "refresh": "1m",
 "templating": {
  "list": [
   { "name": "Filter" }
  ]
 },
 "panels": [
  {
   "title": "RIB insert durations",
   "type": "heatmap",
   "description": "Based on samples taken at infrequent intervals.",
   "gridPos": { "h": 7, "w": 11, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(rotonda_rib_merge_update_other_duration_microseconds_bucket{component=\"rib\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "RIB withdrawal durations",
   "type": "heatmap",
   "description": "Based on samples taken at infrequent intervals.",
   "gridPos": { "h": 7, "w": 11, "x": 11, "y": 0 },
   "targets": [
    {
     "expr": "sum(increase(rotonda_rib_merge_update_withdraw_duration_microseconds_bucket{component=\"rib\"}[$__interval])) by (le)",
     "legendFormat": "{{le}}"
    }
   ]
  },
  {
   "title": "Tokio Task TImings",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 22, "x": 0, "y": 7 },
   "targets": [
    {
     "expr": "irate(rotonda_task_total_poll_duration_milliseconds[1m])",
     "legendFormat": "{{component}} poll"
    },
    {
     "expr": "irate(rotonda_task_total_scheduled_duration_milliseconds[1m])",
     "legendFormat": "{{component}} scheduled"
    },
    {
     "expr": "irate(rotonda_task_total_idle_duration_milliseconds[1m])",
     "legendFormat": "{{component}} idle"
    }
   ]
  },
  {
   "title": "Global RIB Prefix Statistics",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 0, "y": 14 },
   "targets": [
    {
     "expr": "rotonda_rib_unit_num_unique_prefixes_total{component=\"rib\"}",
     "legendFormat": "# unique prefixes seen"
    },
    {
     "expr": "irate(rotonda_rib_unit_num_unique_prefixes_total{component=\"rib\"}[1m])",
     "legendFormat": "# unique prefixes / time"
    },
    {
     "expr": "irate(rotonda_rib_unit_num_insert_retries_total{component=\"rib\"}[1m])",
     "legendFormat": "# insert retries / time"
    }
   ]
  },
  {
   "title": "Global RIB Route Statistics",
   "type": "timeseries",
   "gridPos": { "h": 4, "w": 11, "x": 11, "y": 14 },
   "targets": [
    {
     "expr": "rotonda_rib_unit_num_route_announcements_total{component=\"rib\"}",
     "legendFormat": "# route announcements seen"
    },
    {
     "expr": "rotonda_rib_unit_num_route_withdrawals_total{component=\"rib\"}",
     "legendFormat": "# route withdrawals seen"
    },
    {
     "expr": "rate(rotonda_aggregate_rib_num_route_announcements_total{component=\"rib\"}[$__range])",
     "legendFormat": "# route announcements / time"
    },
    {
     "expr": "rate(rotonda_aggregate_rib_num_route_withdrawals_total{component=\"rib\"}[$__range])",
     "legendFormat": "# route withdrawals / time"
    }
   ]
  },
  {
   "title": "# Unique input prefix count stored per router",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rotonda_bmp_state_num_stored_prefixes_total{component!=\"all\"}",
     "legendFormat": "{{ router }}"
    }
   ]
  },
  {
   "title": "Performance",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 18 },
   "fieldConfig": { "defaults": { "unit": "ms" } },
   "targets": [
    {
     "expr": "rotonda_rib_unit_e2e_duration_milliseconds{component=\"rib\"}",
     "legendFormat": "{{ router }} e2e delay"
    },
    {
     "expr": "avg(rotonda_rib_unit_e2e_duration_milliseconds{component=\"rib\"})",
     "legendFormat": "average e2e delay",
     "visualQuery": {
      "labels": [],
      "metric": "rotonda_global_rib_e2e_delay_milliseconds",
      "operations": []
     }
    },
    {
     "expr": "rotonda_rib_unit_insert_duration_microseconds{component=\"rib\"}",
     "legendFormat": "insert duration"
    }
   ]
  },
  {
   "title": "Rate of problematic updates per router",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "irate(rotonda_rib_unit_num_unusable_bmp_updates_total[1m])",
     "legendFormat": "{{ router }} unusable"
    },
    {
     "expr": "irate(rotonda_bmp_state_num_unusable_config_bmp_updates_total[1m])",
     "legendFormat": "{{ router }} retried"
    },
    {
     "expr": "irate(rotonda_bmp_state_num_peer_unknown_bmp_updates_total[1m])",
     "legendFormat": "{{ router }} peer unknown"
    }
   ]
  },
  {
   "title": "Message receive statistics",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 23 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(irate(rotonda_bmp_tcp_in_num_bmp_messages_received_total[5m]))",
     "legendFormat": "{{ router }} success",
     "visualQuery": {
      "labels": [],
      "metric": "rotonda_global_rib_e2e_delay_total",
      "operations": []
     }
    },
    {
     "expr": "sum(irate(rotonda_bmp_tcp_in_num_receive_io_errors_total[5m]))",
     "legendFormat": "{{ router }} error"
    }
   ]
  },
  {
   "title": "# Dumping peers per router",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 0, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rotonda_bmp_state_num_up_peers_dumping_total{}",
     "legendFormat": "{{ router }}"
    }
   ]
  },
  {
   "title": "# Re-initiation events per router",
   "type": "timeseries",
   "gridPos": { "h": 5, "w": 11, "x": 11, "y": 28 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rotonda_bmp_tcp_in_reconnection_count_total{router!=\"unknown\"}",
     "legendFormat": "{{ router }}"
    }
   ]
  },
  {
   "title": "Router Insight",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 0, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "count(rotonda_bmp_state_num_up_peers_total)",
     "legendFormat": "# routers"
    },
    {
     "expr": "count(rotonda_bmp_state_num_up_peers_dumping_total{}>0)",
     "legendFormat": "# EoR capable routers with at least one pending EoR"
    },
    {
     "expr": "count(rotonda_bmp_state_num_up_peers_dumping_total{}>0)/count(rotonda_bmp_state_num_up_peers_total)",
     "legendFormat": "% EoR capable routers with at least one pending EoR"
    }
   ]
  },
  {
   "title": "Peer Insight (over all routers)",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 7, "x": 7, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "sum(rotonda_bmp_state_num_up_peers_total)",
     "legendFormat": "# of up peers"
    },
    {
     "expr": "sum(rotonda_bmp_state_num_up_peers_dumping_total)",
     "legendFormat": "# of up peers with pending EoR"
    },
    {
     "expr": "sum(rotonda_bmp_state_num_up_peers_dumping_total)/sum(rotonda_bmp_state_num_up_peers_total)",
     "legendFormat": "% of up peers with pending EoR"
    }
   ]
  },
  {
   "title": "Internal Diagnostics",
   "type": "timeseries",
   "gridPos": { "h": 10, "w": 8, "x": 14, "y": 33 },
   "fieldConfig": { "defaults": { "unit": "none" } },
   "targets": [
    {
     "expr": "rotonda_link_capacity_total{}",
     "legendFormat": "component \"{{ component }}\" gate capacity"
    },
    {
     "expr": "sum(rotonda_bmp_tcp_out_handler_state_state{}==0)",
     "legendFormat": "# terminated proxy handlers"
    },
    {
     "expr": "sum(rotonda_bmp_tcp_out_handler_state_state{}==1)",
     "legendFormat": "# proxy handlers waiting to connect"
    },
    {
     "expr": "sum(rotonda_bmp_tcp_out_handler_state_state{}==2)",
     "legendFormat": "# connected proxy handlers "
    },
    {
     "expr": "rotonda_metric_assemble_duration_milliseconds",
     "legendFormat": "metric assembly duration (ms)"
    }
   ]
  }
 ]
}