.TH "rotonda" "1" "NLnet Labs"
.SH NAME
rotonda - a modular analytical BGP engine
.SH SYNOPSIS

.B rotonda
[options]


.SH DESCRIPTION
Roll your own BGP/BMP applications with programmable RIBs and Filters

For more information please consult the online documentation at:
    https://rotonda.docs.nlnetlabs.nl/

.SH OPTIONS
The available options are:

.TP
.BI \-c\  path \fR,\ \fB\-\-config= path
Specify the path to the config file to load.

.TP
.BI -h,\ --help
Prints help information

.TP
.BI -V,\ --version
Prints version information

.SH OPTIONS RELATED TO LOGGING

.TP
.BI -q,\ --quiet
Log less information, twice for no information

.TP
.BI -v,\ --verbose
Log more information, twice or thrice for even more

.TP
.BI --logfile= path
Log to this file

.TP
.BI --syslog
Log to syslog

.TP
.BI --syslog-facility= facility
Facility to use for syslog logging [default: daemon]
