[package]
name = "mrtin"
version.workspace = true
edition.workspace = true
authors.workspace = true
rust-version.workspace = true

[lib]


[dependencies]
inetnum = "0.1.0"
memmap2 = "0.9"
octseq = { version = "0.4.0" }
rotonda-store = { path = "../../rotonda-store" }
routecore = { workspace = true }

[dev-dependencies]
rotonda-store = { path = "../../rotonda-store" }

[[bin]]
name = "test_store"
