name: ci

on:
  push:
    branches:
      - main

  pull_request:

  workflow_dispatch:

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    steps:
    - uses: actions/checkout@v3
    - name: Ensure correct Rust toolchain version
      uses: actions-rs/toolchain@v1
      with:
        toolchain: stable
    - name: Build
      run: cargo build --verbose
    - name: Run tests
      run: cargo test --verbose
