name: coverage

on:
  workflow_dispatch:

jobs:
  coverage:
    name: coverage
    runs-on: self-hosted
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install cargo-tarpaulin if needed
        run: cargo install --locked cargo-tarpaulin

      - name: Generate cargo-tarpaulin code coverage reports
        run: cargo tarpaulin --verbose --out Html --out Xml

      - name: Upload HTML report to GH Actions workflow artifacts
        uses: actions/upload-artifact@v3
        with:
          name: code-coverage-report
          path: tarpaulin-report.html

      - name: Generate Markdown coverage report
        uses: irongut/CodeCoverageSummary@v1.3.0
        with:
          filename: cobertura.xml
          format: markdown
          output: both
      
      - name: Add Markdown coverage report to workflow summary
        run: |
          cat code-coverage-results.md >> $GITHUB_STEP_SUMMARY
          echo >> $GITHUB_STEP_SUMMARY
          echo "See the HTML report for more details (see the `code-coverage-report` workflow artifact)">> $GITHUB_STEP_SUMMARY