name: Docker Packaging

# Manually invoking required
on:

  workflow_dispatch:


jobs:
  docker_only:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7
    secrets:
      DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    with:
      package_test_scripts_path: pkg/test-scripts/test-<package>.sh

      docker_org: nlnetlabs
      docker_repo: rotonda
      docker_build_rules: |
        include:
          - platform:    'linux/amd64'
            shortname:   'amd64'
            mode:        'build'

          - platform:    'linux/arm64'
            shortname:   'arm64'
            crosstarget: 'aarch64-unknown-linux-musl'
            mode:        'copy'
