name: Docker Packaging

# Manually invoking required
on:

  workflow_dispatch:


jobs:
  dockeronly:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7
    secrets:
      DOCKER_HUB_ID: ${{ secrets.DOCKER_HUB_ID }}
      DOCKER_HUB_TOKEN: ${{ secrets.DOCKER_HUB_TOKEN }}

    with:
      docker_org: nlnetlabs
      docker_repo: rotonda
