name: Packaging

on:
  push:
    branches:
      - main
    tags:
      - v*

  # Triggering on PRs and arbitrary branch pushes is not enabled because most of the time only the CI build should be
  # triggered, not the packaging build. In cases where you want to test changes to this workflow this trigger enables
  # you to manually invoke this workflow on an arbitrary branch as needed.
  workflow_dispatch:

jobs:
  full:
    uses: NLnetLabs/ploutos/.github/workflows/pkg-rust.yml@v7

    # Placeholder configuration to make the workflow appear in GitHub Actions until the real workflow is merged to
    # the main branch.
